name: Swift

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: PODS
      run: pod install
    - name: OPEN WORKSPACE 
      run: open CoreDataDemo.xcworkspace
    - name: Build
      run: xcodebuild -scheme CoreDataDemo test -destination "platform=iOS Simulator,name=iPhone 13"
    - name: SOMETHING
      run: echo "SANYA PRIVET"
